import 'dart:async';

Future<void> main() async {
  final usuario = UsuarioRepository();
  usuario.salvarComum((success) {
    print('Sucesso: $success');
  }, (error) {
    print('Erro: $error');
  });

  try {
    final sucesso = await usuario.salvarCompleter();
    print('Sucesso completer: $sucesso');
  } catch (e) {
    print('Erro completer: $e');
  }
}

class UsuarioRepository {
  void salvarComum(void Function(String) callbackSuccess,
      void Function(String) callbackError) {
    Timer(Duration(seconds: 2), () {
      try {
        // throw Exception();
        callbackSuccess('Usu치rio salvo com sucesso');
      } catch (e) {
        callbackError('Erro ao salvar usu치rio');
      }
    });
  }

  Future<String> salvarCompleter() {
    final completer = Completer<String>();
    Timer(Duration(seconds: 2), () {
      try {
        // throw Exception();
        completer.complete('Usu치rio salvo com sucesso');
      } catch (e) {
        completer.completeError('Erro ao salvar usu치rio');
      }
    });
    return completer.future;
  }
}
